# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: CI
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerconn'
        repository: 'selvanregistry'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: CD
  displayName: CD Stage
  dependsOn: CI
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment:  xyz
    strategy: 
      runOnce:
        deploy:
          steps: 
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              manifests: azure-vote-all-in-one-redis.yaml


